env:
  es2021: true
  node: true
extends:
  - standard
  - plugin:react/recommended
  - plugin:react/jsx-runtime
settings:
  react:
    version: 'detect'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - immutable
rules: 
  arrow-parens:
    - warn
    - as-needed
  quotes:
    - warn
    - single
  semi:
    - warn
    - never
  indent:
    - warn
    - 2
    - SwitchCase: 1
      ignoredNodes:
        - ConditionalExpression
  no-var:
    - warn
  no-unused-vars:
    - warn
  immutable/no-let:
    - error
  immutable/no-this:
    - error
  immutable/no-mutation:
    - error
  react/react-in-jsx-scope: 'off'
  react/prop-types: 'off'
  import/order:
    - warn
    - groups:
      - builtin
      - external
      - internal
      - parent
      - sibling
      - index